// Builds src/bridge.ts into a single, offline-capable HTML file for the rn-confidential WebView.
//
// The tricky part: @solana/zk-sdk ships three wasm-bindgen targets (node/bundler/web), and
// @solana-program/token-2022's confidential helpers hard-import the "bundler" target
// (`@solana/zk-sdk/bundler`). That target does `import * as wasm from "./index_bg.wasm"` and
// expects the *bundler* to instantiate the wasm module and hand back its exports as an ES module
// namespace — a convention native to webpack/Vite, which esbuild does not implement. The "web"
// target instead exports a plain async `init(bytes)` function that calls `WebAssembly.instantiate`
// directly on whatever bytes you hand it — exactly what we need for inlined base64, no fetch.
// (Verified: passing raw bytes to `init` skips the target's URL/fetch branch entirely.)
//
// So: alias both `@solana/zk-sdk/bundler` and `@solana/zk-sdk/web` to a "web"-target build for
// this whole bundle — our own, vendor/zk-sdk-web (see ZK_SDK_COMPAT_DIR). The targets export
// identically-named classes (same wasm-bindgen source, different JS glue only), so token-2022's
// import and bridge.ts's own import resolve to the very same module instance — meaning the one
// `zkInit(...)` call in bridge.ts initializes it for both. (esbuild warns about `import.meta` in
// that glue: it's only on the fetch-by-URL path, which passing bytes skips.)
import { build } from 'esbuild'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(fileURLToPath(import.meta.url))
// Not the npm package's own "web" build: a rebuild of the same version without WebAssembly
// reference types, so the bridge also runs on WebViews older than Chrome 96 (see
// scripts/build-zk-sdk-compat.sh, which regenerates it). Same public API, so imports of
// `@solana/zk-sdk/web` (types included) are unchanged — only the bundle is redirected.
const ZK_SDK_COMPAT_DIR = join(ROOT, 'vendor', 'zk-sdk-web')
const ZK_SDK_WASM_PATH = join(ZK_SDK_COMPAT_DIR, 'index_bg.wasm')
const GENERATED_DIR = join(ROOT, 'src', 'generated')
const DIST_DIR = join(ROOT, 'dist')

function generateWasmBase64Module(): void {
  const wasmBytes = readFileSync(ZK_SDK_WASM_PATH)
  const base64 = wasmBytes.toString('base64')
  mkdirSync(GENERATED_DIR, { recursive: true })
  writeFileSync(
    join(GENERATED_DIR, 'wasmBase64.ts'),
    `// Generated by build.ts from @solana/zk-sdk's "web" target wasm binary. Do not edit.\nexport const ZK_SDK_WASM_BASE64 = ${JSON.stringify(base64)};\n`,
  )
  console.log(`embedded ${(wasmBytes.byteLength / 1024).toFixed(0)}KB of wasm as base64`)
}

// Runs before the bundle, in plain ES5 so it parses on any WebView. Phones without Google services
// (e.g. Huawei) ship their own WebView that the Play Store can't update, often a few Chrome
// versions behind; the bundle's syntax is lowered (see `target`), but newer *APIs* it calls need
// these shims. And if the bridge still fails to start, report why — with the engine version — to
// the host instead of leaving it waiting forever (CBridgeHost shows it).
const PRELUDE = `(function () {
  function report(message) {
    try {
      window.ReactNativeWebView.postMessage(JSON.stringify({ bridgeError: String(message), userAgent: navigator.userAgent }))
    } catch (e) {}
  }
  try {
    window.ReactNativeWebView.postMessage(JSON.stringify({ bridgeInfo: true, userAgent: navigator.userAgent }))
  } catch (e) {}
  window.addEventListener('error', function (e) { report((e.error && e.error.stack) || e.message) })
  window.addEventListener('unhandledrejection', function (e) {
    var r = e.reason
    report((r && (r.stack || r.message)) || r)
  })
  if (!Object.hasOwn) {
    Object.hasOwn = function (o, k) { return Object.prototype.hasOwnProperty.call(o, k) }
  }
  if (!Array.prototype.at) {
    Object.defineProperty(Array.prototype, 'at', {
      configurable: true, writable: true,
      value: function (i) { i = Math.trunc(i) || 0; if (i < 0) i += this.length; return this[i] }
    })
  }
  if (typeof AbortSignal !== 'undefined' && !AbortSignal.any) {
    AbortSignal.any = function (signals) {
      var controller = new AbortController()
      for (var i = 0; i < signals.length; i++) {
        var s = signals[i]
        if (s.aborted) { controller.abort(s.reason); break }
        s.addEventListener('abort', (function (s) { return function () { controller.abort(s.reason) } })(s), { once: true })
      }
      return controller.signal
    }
  }
})()`

function wrapAsHtml(js: string): string {
  return `<!doctype html>
<html>
  <head><meta charset="utf-8" /></head>
  <body>
    <script>${PRELUDE}</script>
    <script>${js}</script>
  </body>
</html>
`
}

async function main() {
  generateWasmBase64Module()

  const result = await build({
    entryPoints: [join(ROOT, 'src', 'bridge.ts')],
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'browser',
    // Lowered past es2022 for older, non-updatable WebViews (see PRELUDE). The zk-sdk wasm itself
    // needs reference-types (Chrome 96), so going lower than that wouldn't help.
    target: ['chrome90'],
    alias: {
      '@solana/zk-sdk/bundler': join(ZK_SDK_COMPAT_DIR, 'index.js'),
      '@solana/zk-sdk/web': join(ZK_SDK_COMPAT_DIR, 'index.js'),
    },
    define: {
      'process.env.NODE_ENV': '"production"',
    },
    logLevel: 'info',
  })

  const js = result.outputFiles[0].text
  const html = wrapAsHtml(js)

  mkdirSync(DIST_DIR, { recursive: true })
  writeFileSync(join(DIST_DIR, 'bridge.html'), html)
  writeFileSync(
    join(DIST_DIR, 'bridge-html.ts'),
    `// Generated by build.ts. Do not edit.\nexport const BRIDGE_HTML = ${JSON.stringify(html)};\n`,
  )

  console.log(`wrote dist/bridge.html (${(html.length / 1024).toFixed(0)}KB)`)
}

main().catch((err) => {
  console.error(err)
  process.exitCode = 1
})
