// Builds src/bridge.ts into a single, offline-capable HTML file for the rn-confidential WebView.
//
// The tricky part: @solana/zk-sdk ships three wasm-bindgen targets (node/bundler/web), and
// @solana-program/token-2022's confidential helpers hard-import the "bundler" target
// (`@solana/zk-sdk/bundler`). That target does `import * as wasm from "./index_bg.wasm"` and
// expects the *bundler* to instantiate the wasm module and hand back its exports as an ES module
// namespace — a convention native to webpack/Vite, which esbuild does not implement. The "web"
// target instead exports a plain async `init(bytes)` function that calls `WebAssembly.instantiate`
// directly on whatever bytes you hand it — exactly what we need for inlined base64, no fetch.
// (Verified: passing raw bytes to `init` skips the target's URL/fetch branch entirely.)
//
// So: alias `@solana/zk-sdk/bundler` to `@solana/zk-sdk/web` for this whole bundle. Both targets
// export identically-named classes (same wasm-bindgen source, different JS glue only), so
// token-2022's import and bridge.ts's own import resolve to the very same module instance —
// meaning the one `zkInit(...)` call in bridge.ts initializes it for both.
import { build } from 'esbuild'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(fileURLToPath(import.meta.url))
const ZK_SDK_WASM_PATH = join(ROOT, '..', '..', 'node_modules', '@solana', 'zk-sdk', 'dist', 'web', 'index_bg.wasm')
const GENERATED_DIR = join(ROOT, 'src', 'generated')
const DIST_DIR = join(ROOT, 'dist')

function generateWasmBase64Module(): void {
  const wasmBytes = readFileSync(ZK_SDK_WASM_PATH)
  const base64 = wasmBytes.toString('base64')
  mkdirSync(GENERATED_DIR, { recursive: true })
  writeFileSync(
    join(GENERATED_DIR, 'wasmBase64.ts'),
    `// Generated by build.ts from @solana/zk-sdk's "web" target wasm binary. Do not edit.\nexport const ZK_SDK_WASM_BASE64 = ${JSON.stringify(base64)};\n`,
  )
  console.log(`embedded ${(wasmBytes.byteLength / 1024).toFixed(0)}KB of wasm as base64`)
}

function wrapAsHtml(js: string): string {
  return `<!doctype html>
<html>
  <head><meta charset="utf-8" /></head>
  <body>
    <script>${js}</script>
  </body>
</html>
`
}

async function main() {
  generateWasmBase64Module()

  const result = await build({
    entryPoints: [join(ROOT, 'src', 'bridge.ts')],
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'browser',
    target: ['es2022'],
    alias: {
      '@solana/zk-sdk/bundler': '@solana/zk-sdk/web',
    },
    define: {
      'process.env.NODE_ENV': '"production"',
    },
    logLevel: 'info',
  })

  const js = result.outputFiles[0].text
  const html = wrapAsHtml(js)

  mkdirSync(DIST_DIR, { recursive: true })
  writeFileSync(join(DIST_DIR, 'bridge.html'), html)
  writeFileSync(
    join(DIST_DIR, 'bridge-html.ts'),
    `// Generated by build.ts. Do not edit.\nexport const BRIDGE_HTML = ${JSON.stringify(html)};\n`,
  )

  console.log(`wrote dist/bridge.html (${(html.length / 1024).toFixed(0)}KB)`)
}

main().catch((err) => {
  console.error(err)
  process.exitCode = 1
})
